version: "3.1"
services:
  db:
    image: postgres:12.4-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash
    environment:
      - COMPOSE_FILE
    volumes:
      - ./projects:/projects
    working_dir: /projects
    ports:
      - "4000:4000"
    depends_on:
      - db
    tty: true
